apiVersion: v1
kind: Service
metadata:
  name: landing-page-sv
  namespace: production
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: tcp-80
  selector:
      run: landing-page

---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: landing-page
 namespace: production
spec:
  selector:
    matchLabels:
      run: landing-page
  replicas: 2
  template:
    metadata:
      labels:
        run: landing-page
    spec:
      containers:
      - name: landing-page
        image: dap123/landing-page:latest
        ports:
          - containerPort: 80

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: landing-page-ingress
  namespace: production
  annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: doddy.test-cilsy.my.id
    http:
      paths:
      - path: /
        backend:
          serviceName: landing-page-sv
          servicePort: 80

