apiVersion: v1
kind: Service
metadata:
  name: sosmed-pesbuk-sv
  namespace: production
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: tcp-80
  selector:
      run: sosmed-pesbuk

---

apiVersion: apps/v1
kind: Deployment
metadata:
 name: sosmed-pesbuk
 namespace: production
spec:
  selector:
    matchLabels:
      run: sosmed-pesbuk
  replicas: 2
  template:
    metadata:
      labels:
        run: sosmed-pesbuk
    spec:
      containers:
      - name: sosmed-pesbuk
        image: dap123/social-media-cilsy:latest
        ports:
          - containerPort: 80
        env:
          - name: DB_HOST
            value: 3.141.141.128
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: p-secret-db
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: p-secret-db                
                key: DB_PASS

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sosmed-ingress
  namespace: production
spec:
  rules:
  - host: pesbuk.test-cilsy.my.id 
    http:
      paths:
      - path: /
        backend:
          serviceName: sosmed-pesbuk-sv
          servicePort: 80
